name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: BiouiAdnane
          outputs: dist/snake.svg

      - name: Generate snake
        run: |
          curl -o dist/snake.svg https://raw.githubusercontent.com/Platane/snk/output/github-contribution-grid-snake.svg

      - name: Push the Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
