name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        run: |
          curl -o github-contribution-grid-snake-dark.svg https://raw.githubusercontent.com/Platane/snk/output/github-contribution-grid-snake-dark.svg
          curl -o github-contribution-grid-snake-light.svg https://raw.githubusercontent.com/Platane/snk/output/github-contribution-grid-snake.svg
          mkdir -p dist
          mv github-contribution-grid-snake-dark.svg dist/
          mv github-contribution-grid-snake-light.svg dist/

      - name: Push the Snake to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
