name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: BiouiAdnane
          outputs: dist/snake.svg

      - name: Create output directory if not exists
        run: mkdir -p dist

      - name: Copy Snake to output directory
        run: cp dist/snake.svg dist/github-contribution-grid-snake.svg

      - name: Push the Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
